EXPORTS
    whisper_init_from_file
    whisper_init_from_file_with_params
    whisper_init_from_buffer
    whisper_init_from_buffer_with_params
    whisper_free
    whisper_free_state
    whisper_free_params
    whisper_free_context_params
    whisper_full_default_params
    whisper_full_default_params_by_ref
    whisper_context_default_params
    whisper_context_default_params_by_ref
    whisper_full
    whisper_full_with_state
    whisper_full_parallel
    whisper_full_n_segments
    whisper_full_get_segment_text
    whisper_full_get_segment_t0
    whisper_full_get_segment_t1
    whisper_lang_auto_detect
    whisper_lang_auto_detect_with_state
    whisper_n_len
    whisper_n_vocab
    whisper_n_text_ctx
    whisper_n_audio_ctx
    whisper_is_multilingual
    whisper_print_system_info
    whisper_version
    whisper_token_eot
    whisper_token_sot
    whisper_token_solm
    whisper_token_prev
    whisper_token_nosp
    whisper_token_not
    whisper_token_beg
    whisper_token_lang
    whisper_token_translate
    whisper_token_transcribe
    whisper_token_to_str
    whisper_model_type_readable
    whisper_pcm_to_mel
    whisper_set_mel
    whisper_encode
    whisper_decode
